FROM jupyter/scipy-notebook

RUN pip install --upgrade pip

RUN pip install \
pandas \
numpy \
matplotlib \
seaborn \
scipy \
statsmodels \
scikit-learn \
xgboost \
lightgbm \
catboost

WORKDIR /home/tjordan/housing